### ISSUE TITLE
Feature-Request: Custom Key Labels

### ISSUE THREAD

**Issue by hepiyellow** [garynewby/GLNPianoView#6]
I would like to be able to :
- Display only Key name without Octave (e.g. , "C", "D",... instead of "C4", "D4"
OR
- Display "Do", "Re", "Mi",...

I suggest:
```
pianoView.setKeyLabels(labels: [Int:String])
```
Where `labels` is a dictionary of [MidiNote : Label]

Alternatively, `labels` could be a simple array of a fixed size of 128, to set ALL labels.

**Comment by garynewby** [comment]
You seem to have many specific requirement, might I suggest you maintain your own fork instead?

**Comment by garynewby** [comment]
Addressed in 1.0.18
